services:
  chatbot:
    build: .
    container_name: voice-ecommerce-chatbot
    ports:
      - "8000:8000"
      - "8501:8501"
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      # Mount your local code into the container so you can edit files 
      # and see changes instantly without rebuilding the image!
      - .:/app
      - ./hf_cache:/root/.cache/huggingface